[package]
name = "edit"
version = "0.8.2"
authors = ["Brian Pearce"]
publish = false
edition = "2024"

[lib]
doctest = false
test = false

[dependencies]
common = { path = "../common" }
libc   = "0.2.66"
