[package]
name = "common"
version = "0.8.2"
authors = ["Brian Pearce"]
publish = false
edition = "2024"

[dependencies]
dirs  = "6.0.0"
rand  = "0.9.2"
serde = { version = "1.0.103", features = ["derive"] }
serde-saphyr = "0.0.6"

[dev-dependencies]